# application: swimmingholebot
runtime: python27
threadsafe: yes
# version: 10

handlers:
- url: .*
  script: simpleechobot.app

libraries:
- name: webapp2
  version: 2.5.2
- name: ssl
  version: latest